import type { SceneContract } from './types'
import timing from './timing.json'
import { Cover } from '../scenes/Cover'
import { Signals } from '../scenes/Signals'
import { Threshold } from '../scenes/Threshold'
import { VisionGrammar } from '../scenes/VisionGrammar'
import { EdgePipeline } from '../scenes/EdgePipeline'
import { AgentAnatomy } from '../scenes/AgentAnatomy'
import { Loop } from '../scenes/Loop'
import { CameraLab } from '../scenes/CameraLab'
import { Incident } from '../scenes/Incident'
import { MultiAgent } from '../scenes/MultiAgent'
import { HumanGate } from '../scenes/HumanGate'
import { Pilot } from '../scenes/Pilot'
import { Metrics } from '../scenes/Metrics'
import { AecCriterion } from '../scenes/AecCriterion'
import { Closing } from '../scenes/Closing'

const t = (id: string) => {
  const entry = timing.scenes.find((scene) => scene.id === id)
  if (!entry) throw new Error(`Sin timing para la escena ${id}`)
  return entry
}

export const scenes: SceneContract[] = [
  {
    id: 'cover',
    eyebrow: 'APERTURA',
    claim: 'Cuando la obra puede ver, el agente puede actuar.',
    narrativeRole: 'Apertura sensorial: instala la tesis y el lenguaje visual (obra, cámara, señal, agente).',
    evidence: ['S1', 'S2', 'S5'],
    speakerIntent: 'Provocar la pregunta: ¿y si la obra no solo registrara lo que pasó, sino que activara una acción verificable?',
    transitionIn: 'Desde oscuridad: la silueta de obra y la señal ya están vivas al entrar.',
    transitionOut: 'La señal que viaja queda sin destino: “¿qué pasa hoy con esas señales?” → fractura.',
    durationInFrames: t('cover').durationInFrames,
    stableFrame: t('cover').stableFrame,
    media: [
      { id: 'clip-opening', kind: 'clip', file: 'media/clips/opening.mp4' },
      { id: 'poster-opening', kind: 'poster', file: 'media/posters/opening.png' },
    ],
    interaction: { kind: 'clip', fallback: 'La escena funciona completa sin el clip: la silueta animada es el respaldo.' },
    notes: {
      intent: 'Instalar la tesis sin explicarla todavía. Tono sobrio, casi documental.',
      opening: '“Toda obra ya está siendo observada. La pregunta es qué pasa después de la imagen.”',
      explanation: 'Presentarse breve. Señalar la silueta: una cámara detecta, una señal viaja, un agente espera. Ese recorrido es toda la ponencia.',
      transition: '“Hoy esa señal existe. Lo que no existe es lo que viene ahora.”',
      cue: 'Opcional: reproducir el clip de apertura antes de hablar (botón ▶ en la firma).',
    },
    render: () => <Cover />,
  },
  {
    id: 'signals',
    eyebrow: 'ACTO I · LA FRACTURA',
    claim: 'La obra ya produce señales. Ninguna cierra una decisión.',
    narrativeRole: 'El problema real: información fragmentada que no se convierte en acción a tiempo.',
    evidence: ['S3', 'S6'],
    speakerIntent: 'Que cada asistente reconozca su obra en los seis emisores de señales.',
    transitionIn: 'Las señales entran en fila, como llegan en la vida real: sueltas.',
    transitionOut: '“El problema no es de datos, es de sistema” → ¿qué clase de sistema? Umbral.',
    durationInFrames: t('signals').durationInFrames,
    stableFrame: t('signals').stableFrame,
    notes: {
      intent: 'Aterrizar el dolor cotidiano sin culpar a nadie.',
      opening: '“¿Cuántas fuentes de información tiene hoy su obra? Nosotros contamos al menos seis.”',
      explanation: 'Recorrer los seis emisores. Subrayar la fractura: entre la señal y la decisión hay personas buscando, interpretando y escalando a mano. La decisión llega tarde no por negligencia, sino por diseño.',
      transition: '“Para cerrar ese corte no necesitamos más señales. Necesitamos otro tipo de sistema.”',
    },
    render: () => <Signals />,
  },
  {
    id: 'threshold',
    eyebrow: 'ACTO I · EL UMBRAL',
    claim: 'Un asistente responde. Un agente persigue un objetivo.',
    narrativeRole: 'Umbral conceptual: define agente sin hype y descarta el chatbot como solución.',
    evidence: ['S1'],
    speakerIntent: 'Vacunar contra la confusión asistente/agente antes de hablar de visión.',
    transitionIn: 'Dos lados del umbral: el izquierdo muere en el chat, el derecho continúa.',
    transitionOut: '“¿Y cómo percibe la obra ese agente? Con visión.” → percepción.',
    durationInFrames: t('threshold').durationInFrames,
    stableFrame: t('threshold').stableFrame,
    notes: {
      intent: 'Precisión conceptual: no todo chatbot es agente.',
      opening: '“Casi todos hemos usado un asistente. Muy pocos hemos operado con un agente.”',
      explanation: 'Contrastar: pregunta→respuesta vs objetivo→acción→verificación. El agente mantiene estado, usa herramientas y no termina hasta cerrar el resultado.',
      transition: '“Un agente necesita percibir la obra. Y ahí entra la visión computacional.”',
      warning: 'Escena conceptual: no prometer autonomía total; el matiz llega en gobernanza.',
    },
    render: () => <Threshold />,
  },
  {
    id: 'vision-grammar',
    eyebrow: 'ACTO II · PERCEPCIÓN',
    claim: 'La visión no “entiende la obra”: convierte píxeles en eventos.',
    narrativeRole: 'Alfabetiza: cuatro operaciones de CV sobre el mismo encuadre.',
    evidence: ['S2'],
    speakerIntent: 'Dar vocabulario para conversar con proveedores: clasificar ≠ detectar ≠ segmentar ≠ seguir.',
    transitionIn: 'El mismo frame cambia de overlay según la operación activa.',
    transitionOut: '“Ese evento recién nacido tiene que viajar” → arquitectura.',
    durationInFrames: t('vision-grammar').durationInFrames,
    stableFrame: t('vision-grammar').stableFrame,
    interaction: { kind: 'emit-event', fallback: 'El ciclo avanza solo; los chips también responden al tacto/click.' },
    notes: {
      intent: 'Desmontar la magia: la visión responde preguntas concretas.',
      opening: '“La visión computacional no entiende la obra. Responde cuatro preguntas — y elegir bien la pregunta es el proyecto.”',
      explanation: 'Recorrer las 4 operaciones sobre el mismo encuadre: qué ocurre (clasifica), dónde (detecta), qué área (segmenta), cómo cambia (sigue). El caso de uso define cuál se necesita.',
      transition: '“Cuando la respuesta es útil, se convierte en un evento. Veamos dónde nace.”',
      cue: 'Los chips avanzan solos cada ~3 s; tocar un chip fija la operación.',
    },
    render: () => <VisionGrammar />,
  },
  {
    id: 'edge-pipeline',
    eyebrow: 'ACTO II · ARQUITECTURA',
    claim: 'El evento nace cerca de la cámara. La acción, cerca del contexto.',
    narrativeRole: 'El viaje del evento: cámara → edge → evento → agente → humano → evidencia.',
    evidence: ['S2', 'S4'],
    speakerIntent: 'Explicar el edge en lenguaje operativo: continuidad, ancho de banda, robustez.',
    transitionIn: 'El payload del evento recorre las seis estaciones.',
    transitionOut: '“¿Y qué es exactamente ese agente que recibe el evento?” → anatomía.',
    durationInFrames: t('edge-pipeline').durationInFrames,
    stableFrame: t('edge-pipeline').stableFrame,
    notes: {
      intent: 'Bajar la arquitectura a decisiones operativas, no a marcas de hardware.',
      opening: '“Este pequeño paquete — persona, zona, hora — es el protagonista de la arquitectura.”',
      explanation: 'Seguir el payload por las estaciones. El edge filtra e infiere local: menos ancho de banda, operación con red inestable, buffer y reintentos. La fila de estados de salud muestra que esto se opera, no se instala y se olvida.',
      transition: '“El evento ya llegó al agente. Abramos al agente.”',
    },
    render: () => <EdgePipeline />,
  },
  {
    id: 'agent-anatomy',
    eyebrow: 'ACTO II · ANATOMÍA',
    claim: 'Un agente útil no es un chatbot con nombre. Es un sistema con límites.',
    narrativeRole: 'Las seis capas del agente; el modelo es solo una pieza.',
    evidence: ['S1'],
    speakerIntent: 'Que un directivo sepa qué exigir cuando le vendan “un agente”.',
    transitionIn: 'Las capas se apilan en orden: del objetivo a los permisos.',
    transitionOut: '“Con las piezas claras, veamos el sistema girando” → loop.',
    durationInFrames: t('agent-anatomy').durationInFrames,
    stableFrame: t('agent-anatomy').stableFrame,
    notes: {
      intent: 'Checklist mental de compra/diseño de agentes.',
      opening: '“Cuando les ofrezcan un agente, pidan ver estas seis capas. Si falta una, es una demo.”',
      explanation: 'Recorrer objetivo, contexto, herramientas, memoria, verificación, permisos. Cerrar con el antipatrón: un agente que hace todo suele fallar.',
      transition: '“Estas capas quietas no valen nada. Valen cuando giran.”',
    },
    render: () => <AgentAnatomy />,
  },
  {
    id: 'loop',
    eyebrow: 'ACTO II · EL LOOP OPERATIVO',
    claim: 'El agente mantiene vivo el loop: de la señal a la evidencia.',
    narrativeRole: 'El corazón del sistema: seis estados que se encadenan y cierran.',
    evidence: ['S1', 'S2', 'S3'],
    speakerIntent: 'Fijar la imagen mental central de la ponencia: un ciclo con estados y cierre.',
    transitionIn: 'El anillo entra con el barrido ya girando: el sistema está vivo.',
    transitionOut: '“Ahora véanlo con una señal real de cámara” → demo de percepción.',
    durationInFrames: t('loop').durationInFrames,
    stableFrame: t('loop').stableFrame,
    notes: {
      intent: 'Esta es la diapositiva que deben recordar en un año.',
      opening: '“Si se llevan una sola imagen de esta charla, que sea esta.”',
      explanation: 'Narrar el ciclo siguiendo el barrido: percibe, interpreta, decide, actúa, escala, evidencia. Subrayar: la persona aparece antes de la acción crítica y la salida es un cambio de estado registrado.',
      transition: '“Suena abstracto hasta que se ve. Hagámoslo ver.”',
    },
    render: () => <Loop />,
  },
  {
    id: 'camera-lab',
    eyebrow: 'ACTO II · DEMO DE PERCEPCIÓN',
    claim: 'La cámara no es el producto. El producto es el evento.',
    narrativeRole: 'Demostración en vivo del paso imagen → evento estructurado.',
    evidence: ['S2', 'S3'],
    speakerIntent: 'Hacer tangible el payload: zona, cámara, hora, contexto.',
    transitionIn: 'El feed (o su respaldo conceptual) ya escanea al entrar.',
    transitionOut: '“Un evento solo es ruido. Lo que importa es la respuesta completa” → incidente.',
    durationInFrames: t('camera-lab').durationInFrames,
    stableFrame: t('camera-lab').stableFrame,
    media: [
      { id: 'clip-vision', kind: 'clip', file: 'media/clips/vision-to-event.mp4' },
      { id: 'poster-vision', kind: 'poster', file: 'media/posters/vision-to-event.png' },
    ],
    interaction: { kind: 'camera', fallback: 'Sin permiso de cámara: respaldo conceptual + clip visión→evento.' },
    notes: {
      intent: 'Demostrar, no decorar: cada clic produce un evento con estructura.',
      opening: '“Esta cámara es local, no identifica personas y no guarda nada. Lo interesante no es la imagen: es esto.”',
      explanation: 'Emitir 2–3 eventos demo: leer en voz alta el payload (tipo, zona, cámara, hora). Ese paquete es lo que el agente puede usar; la imagen sola, no.',
      transition: '“¿Y qué hace el sistema con ese paquete? Simulémoslo completo.”',
      warning: 'Si la sala no permite cámara: no insistir; el respaldo y el clip cuentan la misma historia.',
      cue: 'Botón “Emitir evento demo” = momento clave; activar cámara solo si el contexto lo permite.',
    },
    render: () => <CameraLab />,
  },
  {
    id: 'incident',
    eyebrow: 'ACTO II · LA DEMOSTRACIÓN',
    claim: 'Una detección crea ruido. Un loop diseñado cierra una respuesta.',
    narrativeRole: 'Demo central: el loop completo sobre un incidente conceptual de seguridad.',
    evidence: ['S1', 'S2', 'S3'],
    speakerIntent: 'Mostrar causalidad de punta a punta: señal → evento → contexto → humano → acción → evidencia.',
    transitionIn: 'El plano de zona en espera crea tensión antes del clic.',
    transitionOut: '“Esto fue un agente. Los procesos reales necesitan varios” → orquestación.',
    durationInFrames: t('incident').durationInFrames,
    stableFrame: t('incident').stableFrame,
    media: [
      { id: 'clip-loop', kind: 'clip', file: 'media/clips/agent-loop.mp4' },
      { id: 'poster-loop', kind: 'poster', file: 'media/posters/agent-loop.png' },
    ],
    interaction: { kind: 'simulation', fallback: 'La secuencia también puede narrarse estática o con el clip agent loop.' },
    notes: {
      intent: 'La escena que convierte escépticos: causalidad visible, humano presente, evidencia final.',
      opening: '“Voy a ejecutar el loop completo. Fíjense dónde aparece la persona.”',
      explanation: 'Ejecutar y narrar cada paso al ritmo de la animación: la señal se vuelve evento con payload; el agente contrasta turno, permiso y criticidad; el responsable SST confirma; la alerta sale con evidencia; todo queda registrado.',
      transition: '“Un loop, un agente. Una obra real tiene decenas de loops — y eso exige orquestación.”',
      warning: 'Decir explícitamente: simulación conceptual, no un despliegue real.',
      cue: 'Botón “Ejecutar el loop”. Repetir una segunda vez si la sala lo pide.',
    },
    render: () => <Incident />,
  },
  {
    id: 'multiagent',
    eyebrow: 'ACTO III · ORQUESTACIÓN',
    claim: 'Un agente que hace todo, falla. Especialistas coordinados cierran procesos.',
    narrativeRole: 'Escala el concepto: especialistas con contratos de entrada/salida bajo un orquestador.',
    evidence: ['S1'],
    speakerIntent: 'Evitar la fantasía del super-agente; instalar la idea de contratos verificables.',
    transitionIn: 'El orquestador aparece primero; los especialistas se conectan debajo.',
    transitionOut: '“¿Y quién controla a los agentes?” → gobernanza.',
    durationInFrames: t('multiagent').durationInFrames,
    stableFrame: t('multiagent').stableFrame,
    notes: {
      intent: 'Arquitectura organizacional, no zoológico de bots.',
      opening: '“La tentación es pedir un agente que lo haga todo. Esa es la receta del fracaso.”',
      explanation: 'Leer los contratos: cada especialista declara qué entra y qué sale verificable. El orquestador coordina, escala y audita.',
      transition: '“Más agentes implica más poder. Y el poder exige límites.”',
    },
    render: () => <MultiAgent />,
  },
  {
    id: 'human-gate',
    eyebrow: 'ACTO III · GOBERNANZA',
    claim: 'Autonomía proporcional al riesgo: lo crítico lo decide una persona.',
    narrativeRole: 'Gobernanza como diseño: espectro de riesgo con punto de control humano.',
    evidence: ['S1', 'S3'],
    speakerIntent: 'Responder el miedo (“¿la IA decide sola?”) con una regla de diseño clara.',
    transitionIn: 'El espectro se tiñe de azul (automático) a naranja (crítico).',
    transitionOut: '“Con límites claros, ¿cómo empezar? Pequeño.” → piloto.',
    durationInFrames: t('human-gate').durationInFrames,
    stableFrame: t('human-gate').stableFrame,
    notes: {
      intent: 'Convertir el temor en criterio de diseño.',
      opening: '“La pregunta correcta no es si la IA decide. Es qué decisiones jamás le vamos a delegar.”',
      explanation: 'Recorrer el espectro: lo reversible se automatiza con log; lo crítico cruza el punto de control humano. Citar la regla: más autonomía = más logs + más permisos granulares + más aprobación humana.',
      transition: '“Gobernanza definida. Ahora sí: el primer paso.”',
    },
    render: () => <HumanGate />,
  },
  {
    id: 'pilot',
    eyebrow: 'ACTO III · PRIMER PILOTO',
    claim: 'Empieza con un evento crítico. No con una plataforma.',
    narrativeRole: 'El camino de entrada: tres fases con una pregunta de validación cada una.',
    evidence: ['S2', 'S3', 'S4'],
    speakerIntent: 'Bajar la barrera de entrada: el lunes se puede empezar con una cámara y un evento.',
    transitionIn: 'Tres peldaños ascendentes: observar, validar, escalar.',
    transitionOut: '“¿Y cómo sabremos si funcionó?” → métricas.',
    durationInFrames: t('pilot').durationInFrames,
    stableFrame: t('pilot').stableFrame,
    notes: {
      intent: 'Accionabilidad inmediata sin promesas de precisión.',
      opening: '“No compren una plataforma. Elijan un evento que hoy les duela.”',
      explanation: 'Fase 1: ¿la señal existe con calidad? Fase 2: ¿el evento cambia una decisión real? Fase 3: escalar solo si el loop mantiene calidad y trazabilidad. Sin calibración por obra no se promete precisión.',
      transition: '“Para decidir si el piloto vive o muere, hay que medir lo correcto.”',
    },
    render: () => <Pilot />,
  },
  {
    id: 'metrics',
    eyebrow: 'ACTO III · EVIDENCIA DE VALOR',
    claim: 'No midas cuántas alertas genera. Mide cuántas decisiones mejora.',
    narrativeRole: 'Define el éxito del sistema en términos de decisiones, no de detecciones.',
    evidence: ['S1', 'S2', 'S3'],
    speakerIntent: 'Dejar el criterio de inversión: alertas sin decisión son costo, no valor.',
    transitionIn: 'Cuatro instrumentos en cero: nada se promete de fábrica.',
    transitionOut: '“Las métricas necesitan lectura experta” → rol profesional.',
    durationInFrames: t('metrics').durationInFrames,
    stableFrame: t('metrics').stableFrame,
    notes: {
      intent: 'Honestidad como diferencial: instrumentos sin cifras inventadas.',
      opening: '“Un sistema puede detectar muchísimo y aportar nada.”',
      explanation: 'Recorrer los 4 instrumentos: tiempo de ciclo completo, cobertura de evidencia, calidad (falsos positivos/negativos) e intervención humana. Los valores se calibran en el piloto — desconfíen de quien traiga cifras de fábrica.',
      transition: '“¿Y quién lee estos instrumentos con criterio? Ustedes.”',
    },
    render: () => <Metrics />,
  },
  {
    id: 'aec-criterion',
    eyebrow: 'ACTO III · EL ROL PROFESIONAL',
    claim: 'La IA no reemplaza el criterio de obra. Lo necesita.',
    narrativeRole: 'Cierra la objeción laboral: el profesional AEC como fuente del criterio.',
    evidence: ['S1', 'S2'],
    speakerIntent: 'Que cada profesional salga sintiéndose necesario en este sistema, no amenazado.',
    transitionIn: 'Dos campos se encuentran en una costura: el criterio vive en la unión.',
    transitionOut: 'Última respiración antes del cierre.',
    durationInFrames: t('aec-criterion').durationInFrames,
    stableFrame: t('aec-criterion').stableFrame,
    notes: {
      intent: 'Emoción controlada: reconocimiento del oficio.',
      opening: '“Nada de lo anterior funciona sin alguien que sepa cómo se comporta una obra de verdad.”',
      explanation: 'El dominio de obra aporta la excepción, la secuencia y la seguridad; la capa digital aporta datos y continuidad. El criterio — qué automatizar, qué verificar, qué detener — vive en la costura.',
      transition: '“Y con ese criterio, la invitación final es simple.”',
    },
    render: () => <AecCriterion />,
  },
  {
    id: 'closing',
    eyebrow: 'CIERRE',
    claim: 'No necesitamos una obra llena de IA. Necesitamos una obra que vea, decida y aprenda.',
    narrativeRole: 'Cierre y llamada a la acción: diseñar el primer loop.',
    evidence: ['S1', 'S2', 'S3'],
    speakerIntent: 'Dejar la tarea concreta: un evento crítico, una decisión, una evidencia.',
    transitionIn: 'Las señales convergen y el anillo se completa: el loop queda cerrado.',
    transitionOut: 'Fin. Preguntas.',
    durationInFrames: t('closing').durationInFrames,
    stableFrame: t('closing').stableFrame,
    media: [
      { id: 'clip-closing', kind: 'clip', file: 'media/clips/closing.mp4' },
      { id: 'poster-closing', kind: 'poster', file: 'media/posters/closing.png' },
    ],
    interaction: { kind: 'clip', fallback: 'El anillo convergente animado es el respaldo del clip.' },
    notes: {
      intent: 'Cierre sobrio, memorable y accionable.',
      opening: '“No vinimos a llenar la obra de IA.”',
      explanation: 'Decir la frase completa mirando a la sala. Señalar los tres espacios en blanco: su primer loop cabe en una servilleta — un evento crítico, una decisión, una evidencia.',
      transition: '“Cuando la obra puede ver, el agente puede actuar. Gracias.”',
      cue: 'Opcional: clip de cierre al terminar el aplauso, antes de preguntas.',
    },
    render: () => <Closing />,
  },
]
