import type { SceneContract } from './types'
import timing from './timing.json'
import {
  Agenda,
  AgentAnalogy,
  AiFirstCover,
  AiFirstOperatingModel,
  AiMomentum,
  ChatGptAgentMode,
  ConceptRunway,
  FirstLoop,
  GenIntroFilm,
  GrokExpertTeam,
  HumanAndAi,
  InformationDispersed,
  InnovationAutomationRedesign,
  InternalFirst,
  MarketGap,
  MultiAgentLoop,
  OrchestrationStack,
  ProblemFocus,
  ProofAndClosing,
  TripleImpact,
} from '../scenes/AiFirstKeynote'

const t = (id: string) => {
  const entry = timing.scenes.find((scene) => scene.id === id)
  if (!entry) throw new Error(`Sin timing para la escena ${id}`)
  return entry
}

export const scenes: SceneContract[] = [
  {
    id: 'cover',
    eyebrow: 'APERTURA',
    claim: 'La ventaja no es usar IA. Es entender bien el problema.',
    narrativeRole: 'Abrir con la tesis central y desplazar el foco desde las herramientas hacia el criterio.',
    evidence: ['S5'],
    speakerIntent: 'Crear tensión inmediata: esta no será una charla de herramientas.',
    transitionIn: 'Desde oscuridad, aparece la palabra problema antes que cualquier tecnología.',
    transitionOut: 'La tesis abre una pregunta: ¿qué significa operar con IA dentro de una empresa AEC?',
    durationInFrames: t('cover').durationInFrames,
    stableFrame: t('cover').stableFrame,
    notes: {
      intent: 'Romper la expectativa de un catálogo de apps y prometer un criterio de decisión.',
      opening: '“No vengo a enseñarles veinte herramientas. Vengo a mostrarles qué problema vale la pena resolver.”',
      explanation: 'Presentarse en una frase. La ponencia conectará información dispersa, sistemas agentic y un modelo operativo AI First.',
      transition: '“Antes de hablar de agentes, quiero mostrarles desde dónde construimos esta tesis.”',
    },
    render: () => <AiFirstCover />,
  },
  {
    id: 'film-gen-intro',
    eyebrow: 'GEN+ · INTRO',
    claim: 'La IA no compite con tu gente. Compite con tu desorden.',
    narrativeRole: 'Única pieza cinematográfica: instalar identidad GEN+ e internal-first sin interrumpir el resto del relato.',
    evidence: ['S5', 'S15'],
    speakerIntent: 'Dar una apertura emocional breve y asociar GEN+ con operación, no con discurso tecnológico.',
    transitionIn: 'La tesis de portada se convierte en una secuencia de señales, flujo y acción.',
    transitionOut: 'El logo cede paso al mapa de tres ideas que estructuran la ponencia.',
    durationInFrames: t('film-gen-intro').durationInFrames,
    stableFrame: t('film-gen-intro').stableFrame,
    media: [
      { id: 'clip-opening', kind: 'clip', file: 'media/clips/opening.mp4' },
      { id: 'poster-opening', kind: 'poster', file: 'media/posters/opening.png' },
    ],
    interaction: { kind: 'clip', fallback: 'En movimiento reducido se muestra el poster con la misma tesis.' },
    notes: {
      intent: 'Una sola película para elevar la apertura y evitar saturación audiovisual.',
      opening: 'No hablar durante los primeros segundos.',
      explanation: 'La película presenta la transición desde información fragmentada hacia un loop operativo con control humano.',
      transition: '“Ese recorrido tiene tres partes.”',
      cue: 'Dejar que el film complete un ciclo; después avanzar a la agenda.',
    },
    render: () => <GenIntroFilm />,
  },
  {
    id: 'agenda',
    eyebrow: 'MAPA',
    claim: 'Tres ideas. Una sola tesis.',
    narrativeRole: 'Explicitar la promesa: problema y oportunidad, sistemas agentic y AI First.',
    evidence: ['S1', 'S8', 'S9'],
    speakerIntent: 'Dar orientación y permitir que la audiencia entienda el propósito de cada acto.',
    transitionIn: 'La película deja tres conceptos latentes que ahora se nombran.',
    transitionOut: 'El primer punto exige dimensionar la paradoja del mercado AEC.',
    durationInFrames: t('agenda').durationInFrames,
    stableFrame: t('agenda').stableFrame,
    notes: {
      intent: 'Presentar una estructura simple y acumulativa.',
      opening: '“Vamos a recorrer tres ideas, pero todas responden la misma pregunta: ¿cómo convertimos información en decisiones?”',
      explanation: 'Problema y oportunidad; recorrido flash de agentic AI; modelo operativo AI First.',
      transition: '“Comencemos por la paradoja: un mercado enorme que todavía pierde valor en su forma de operar.”',
    },
    render: () => <Agenda />,
  },
  {
    id: 'market-gap',
    eyebrow: 'ACTO I · PROBLEMA',
    claim: 'La construcción crece. Su productividad no al mismo ritmo.',
    narrativeRole: 'Dimensionar el mercado y la brecha de productividad con datos actuales y comparables.',
    evidence: ['S8'],
    speakerIntent: 'Demostrar que el problema es económicamente relevante y no una moda tecnológica.',
    transitionIn: 'La agenda abre el acto con el tamaño del reto.',
    transitionOut: 'La brecha agregada se vuelve concreta al observar a quién afecta.',
    durationInFrames: t('market-gap').durationInFrames,
    stableFrame: t('market-gap').stableFrame,
    notes: {
      intent: 'Instalar la paradoja: escala enorme, mejora operativa lenta.',
      opening: '“No estamos hablando de un nicho. La construcción movió alrededor de trece trillones de dólares en 2023.”',
      explanation: 'La proyección alcanza US$22T en 2040, mientras la productividad anual 2000–2022 fue 0.4%, frente a 2% de la economía y 3% de manufactura.',
      transition: '“Esa brecha no vive en un gráfico. La pagan las personas, las empresas y los proyectos.”',
      warning: 'Trillón se usa en sentido anglosajón de trillion; al hablar, puede decir “13 millones de millones de dólares”.',
    },
    render: () => <MarketGap />,
  },
  {
    id: 'triple-impact',
    eyebrow: 'ACTO I · IMPACTO',
    claim: 'El mismo problema golpea tres niveles.',
    narrativeRole: 'Traducir la brecha macro en consecuencias para profesional, empresa y proyecto.',
    evidence: ['S3', 'S15'],
    speakerIntent: 'Hacer reconocible el dolor sin inventar cifras específicas.',
    transitionIn: 'El dato macro aterriza en el trabajo cotidiano.',
    transitionOut: 'Los tres impactos comparten una causa: la fragmentación informativa.',
    durationInFrames: t('triple-impact').durationInFrames,
    stableFrame: t('triple-impact').stableFrame,
    notes: {
      intent: 'Alinear a toda la sala: cada rol ve una manifestación distinta del mismo problema.',
      opening: '“El profesional siente búsqueda y retrabajo; la empresa pierde trazabilidad; el proyecto corrige tarde.”',
      explanation: 'No son tres problemas independientes. Nacen de información capturada sin un sistema que cierre decisiones.',
      transition: '“Veamos cómo se produce esa fractura.”',
    },
    render: () => <TripleImpact />,
  },
  {
    id: 'information-dispersed',
    eyebrow: 'ACTO I · FRAGMENTACIÓN',
    claim: 'La información existe. El sistema que la convierte en acción, no.',
    narrativeRole: 'Visualizar los canales desconectados y el cuello de botella de la decisión tardía.',
    evidence: ['S2', 'S3'],
    speakerIntent: 'Lograr que la audiencia reconozca su operación en seis fuentes comunes.',
    transitionIn: 'Los impactos se explican mostrando la arquitectura real del dato.',
    transitionOut: 'La fractura abre la oportunidad: IA ya tiene capital y adopción, pero falta integración.',
    durationInFrames: t('information-dispersed').durationInFrames,
    stableFrame: t('information-dispersed').stableFrame,
    notes: {
      intent: 'Demostrar que el problema no es escasez de datos.',
      opening: '“WhatsApp, Excel, PDF, correo, BIM y reuniones: cada canal sabe algo; ninguno conoce todo.”',
      explanation: 'El cuello de botella es conectar contexto, responsable y criterio de cierre.',
      transition: '“La tecnología para cerrar esta fractura está avanzando a una velocidad extraordinaria.”',
    },
    render: () => <InformationDispersed />,
  },
  {
    id: 'ai-momentum',
    eyebrow: 'ACTO I · OPORTUNIDAD',
    claim: 'El capital y la adopción ya se movieron. El impacto operativo todavía no.',
    narrativeRole: 'Probar la magnitud de la ola de IA sin confundir inversión con valor capturado.',
    evidence: ['S9', 'S11', 'S12'],
    speakerIntent: 'Crear urgencia con prudencia: el mercado decidió la dirección, no el modelo de implementación.',
    transitionIn: 'La fragmentación encuentra una tecnología capaz de procesar y accionar contexto.',
    transitionOut: 'La oportunidad obliga a distinguir innovación, automatización y rediseño.',
    durationInFrames: t('ai-momentum').durationInFrames,
    stableFrame: t('ai-momentum').stableFrame,
    notes: {
      intent: 'Mostrar velocidad de adopción e inversión con fuentes oficiales.',
      opening: '“88% de las organizaciones encuestadas por McKinsey reporta uso regular de IA en al menos una función.”',
      explanation: 'OpenAI anunció US$40B y Anthropic US$13B de financiación en 2025. El capital valida dirección; no garantiza transformación de procesos.',
      transition: '“Para capturar valor necesitamos separar tres verbos que suelen mezclarse.”',
      warning: 'No presentar inversión como prueba de rentabilidad o impacto operativo.',
    },
    render: () => <AiMomentum />,
  },
  {
    id: 'innovation-automation-redesign',
    eyebrow: 'ACTO I · MARCO',
    claim: 'Innovar crea valor. Automatizar reduce fricción. Rediseñar cambia la curva.',
    narrativeRole: 'Introducir el tercer concepto que conecta innovación y automatización con AI First: rediseño.',
    evidence: ['S9', 'S16'],
    speakerIntent: 'Dar un marco memorable que la audiencia pueda aplicar a cualquier iniciativa.',
    transitionIn: 'La ola de IA se convierte en tres opciones estratégicas.',
    transitionOut: 'El rediseño obliga a aclarar la división de trabajo entre IA y humano.',
    durationInFrames: t('innovation-automation-redesign').durationInFrames,
    stableFrame: t('innovation-automation-redesign').stableFrame,
    notes: {
      intent: 'Evitar que toda mejora sea llamada innovación.',
      opening: '“Automatizar es hacer más rápido. Innovar es crear valor nuevo. Rediseñar es cambiar quién hace qué y cómo se decide.”',
      explanation: 'AI First vive principalmente en el tercer verbo: el flujo se diseña desde cero con inteligencia y control humano.',
      transition: '“¿Qué trabajo queda entonces para la persona?”',
    },
    render: () => <InnovationAutomationRedesign />,
  },
  {
    id: 'human-and-ai',
    eyebrow: 'ACTO I · IA + HUMANO',
    claim: 'La IA ya gana pruebas. El humano debe elegir qué problema merece resolver.',
    narrativeRole: 'Corregir el falso duelo humano versus IA y definir fortalezas complementarias.',
    evidence: ['S10'],
    speakerIntent: 'Reducir ansiedad y elevar el papel humano desde ejecución rutinaria hacia criterio y responsabilidad.',
    transitionIn: 'El rediseño necesita repartir capacidades con precisión.',
    transitionOut: 'La ventaja competitiva se concentra en comprender mejor el problema.',
    durationInFrames: t('human-and-ai').durationInFrames,
    stableFrame: t('human-and-ai').stableFrame,
    notes: {
      intent: 'Reconocer el avance técnico sin exagerar autonomía o comprensión.',
      opening: '“En varios benchmarks cerrados la IA ya iguala o supera líneas base humanas.”',
      explanation: 'Eso no equivale a comprender una empresa. La IA aporta escala; el humano define propósito, trade-offs y asume consecuencias.',
      transition: '“Por eso el valor profesional se mueve: de usar herramientas a entender problemas.”',
      warning: 'No decir “supera al humano en todo”. Stanford documenta progreso en tareas específicas y también límites.',
    },
    render: () => <HumanAndAi />,
  },
  {
    id: 'problem-focus',
    eyebrow: 'KEY TAKEAWAY · ACTO I',
    claim: 'El profesional valioso no memorizará herramientas. Entenderá mejor el problema.',
    narrativeRole: 'Cerrar el primer acto con la idea que la audiencia debe recordar.',
    evidence: ['S10', 'S16'],
    speakerIntent: 'Cambiar la aspiración: menos dominio superficial de apps, más capacidad diagnóstica.',
    transitionIn: 'La complementariedad humano-IA se convierte en una prioridad profesional.',
    transitionOut: 'La tesis se prueba primero en la propia empresa.',
    durationInFrames: t('problem-focus').durationInFrames,
    stableFrame: t('problem-focus').stableFrame,
    notes: {
      intent: 'Entregar una frase repetible y defendible.',
      opening: '“Cuando todos pueden crear herramientas, la ventaja vuelve al criterio.”',
      explanation: 'El problema bien entendido especifica quién sufre, dónde se rompe el flujo, qué decisión importa y qué evidencia valida valor.',
      transition: '“¿Dónde es más honesto empezar? Dentro de nuestra propia operación.”',
    },
    render: () => <ProblemFocus />,
  },
  {
    id: 'internal-first',
    eyebrow: 'PUENTE · GEN+',
    claim: 'Si no funciona dentro de tu empresa, todavía no es una oferta.',
    narrativeRole: 'Conectar la tesis con el posicionamiento GEN+ internal-first y la transformación de servicios en sistemas.',
    evidence: ['S15', 'S16'],
    speakerIntent: 'Diferenciar a GEN+ desde práctica operativa y no desde autoridad declarativa.',
    transitionIn: 'Comprender el problema obliga a trabajar con contexto que la propia empresa controla.',
    transitionOut: 'Con el principio claro, el segundo acto recorre la evolución desde IA hasta loops agentic.',
    durationInFrames: t('internal-first').durationInFrames,
    stableFrame: t('internal-first').stableFrame,
    notes: {
      intent: 'Presentar internal-first como principio operativo GEN+, no como estadística universal.',
      opening: '“Primero ordenamos. Luego operamos. Recién después escalamos y vendemos.”',
      explanation: 'GEN+ busca reducir tiempo, error, riesgo y falta de trazabilidad con baseline y evidencia.',
      transition: '“Para hacerlo necesitamos entender, muy rápido, qué cambia de un prompt a un sistema agentic.”',
      warning: 'No afirmar que internal-first garantiza éxito; presentarlo como principio de credibilidad y aprendizaje controlado.',
    },
    render: () => <InternalFirst />,
  },
  {
    id: 'concept-runway',
    eyebrow: 'ACTO II · RECORRIDO FLASH',
    claim: 'De generar respuestas a cerrar trabajo.',
    narrativeRole: 'Explicar en un minuto IA, prompt, asistente, agente, multiagente y loop.',
    evidence: ['S1', 'S13', 'S14'],
    speakerIntent: 'Dar vocabulario suficiente sin convertir la ponencia en un curso introductorio.',
    transitionIn: 'Internal-first necesita una escalera de capacidades concreta.',
    transitionOut: 'La palabra agente se aterriza con una analogía de obra.',
    durationInFrames: t('concept-runway').durationInFrames,
    stableFrame: t('concept-runway').stableFrame,
    notes: {
      intent: 'Recorrido flash, no explicación profunda.',
      opening: '“IA genera capacidad. El prompt instruye. El asistente responde. El agente actúa. El equipo especializa. El loop aprende.”',
      explanation: 'Cada nivel añade autonomía y exige más contexto, permisos, observabilidad y evaluación.',
      transition: '“¿Cómo imaginamos un agente sin jerga técnica? Como una brigada con encargo.”',
    },
    render: () => <ConceptRunway />,
  },
  {
    id: 'agent-analogy',
    eyebrow: 'ACTO II · ANATOMÍA',
    claim: 'Un agente se parece más a una brigada con encargo que a un chat inteligente.',
    narrativeRole: 'Explicar anatomía del agente mediante equivalencias AEC.',
    evidence: ['S1'],
    speakerIntent: 'Convertir un concepto abstracto en un sistema familiar de encargo, planos, herramientas y QA.',
    transitionIn: 'El recorrido flash se detiene en la unidad central: el agente.',
    transitionOut: 'La analogía se conecta con una experiencia que la audiencia ya ha visto: Agent Mode.',
    durationInFrames: t('agent-analogy').durationInFrames,
    stableFrame: t('agent-analogy').stableFrame,
    notes: {
      intent: 'Que la audiencia pueda explicar un agente a otra persona.',
      opening: '“Una cuadrilla necesita encargo, planos, herramientas, bitácora, control de calidad y permiso de trabajo.”',
      explanation: 'Esas seis piezas equivalen a objetivo, contexto, tools, memoria, evaluación y guardrails.',
      transition: '“Ese patrón ya dejó el laboratorio y apareció en las interfaces que usamos.”',
    },
    render: () => <AgentAnalogy />,
  },
  {
    id: 'chatgpt-agent-mode',
    eyebrow: 'ACTO II · YA EXISTE',
    claim: 'El modo agente ya movió la interfaz: de conversar a ejecutar con supervisión.',
    narrativeRole: 'Mostrar un pantallazo conceptual de ChatGPT agent como patrón ya disponible.',
    evidence: ['S13'],
    speakerIntent: 'Generar reconocimiento y demostrar que agentic AI ya forma parte de productos masivos.',
    transitionIn: 'La anatomía se hace visible en una interfaz conocida.',
    transitionOut: 'Un agente puede ejecutar; un equipo puede dividir y revisar trabajo complejo.',
    durationInFrames: t('chatgpt-agent-mode').durationInFrames,
    stableFrame: t('chatgpt-agent-mode').stableFrame,
    notes: {
      intent: 'Pantallazo visual, no tutorial.',
      opening: '“El que menos ha usado ChatGPT ya ha visto esta evolución: plan, acción, narración y control humano.”',
      explanation: 'ChatGPT agent combina investigación, navegador, terminal y conectores; solicita control antes de acciones sensibles.',
      transition: '“El siguiente salto es dividir el objetivo entre especialistas.”',
      warning: 'La UI es una representación conceptual, no una captura exacta del producto.',
    },
    render: () => <ChatGptAgentMode />,
  },
  {
    id: 'grok-expert-team',
    eyebrow: 'ACTO II · TEAM OF EXPERTS',
    claim: 'Grok Build demuestra el patrón: dividir trabajo complejo entre subagentes especializados.',
    narrativeRole: 'Introducir el patrón Team of Experts y reconocer el stack Grok solicitado por el usuario.',
    evidence: ['S14'],
    speakerIntent: 'Mostrar que multiagente significa especialización coordinada, no muchas ventanas de chat.',
    transitionIn: 'La ejecución individual se expande a trabajo paralelo especializado.',
    transitionOut: 'Los modelos se ubican dentro de un stack de orquestación más amplio.',
    durationInFrames: t('grok-expert-team').durationInFrames,
    stableFrame: t('grok-expert-team').stableFrame,
    notes: {
      intent: 'Explicar Team of Experts con una salida unificada.',
      opening: '“Explorar, diseñar, construir y revisar pueden correr en paralelo, pero alguien debe orquestar y sintetizar.”',
      explanation: 'Grok Build documenta subagentes en paralelo y un modo headless para integraciones.',
      transition: '“Grok es una capacidad. Codex, Claude y n8n ocupan otras capas. El valor está en cómo se conectan.”',
    },
    render: () => <GrokExpertTeam />,
  },
  {
    id: 'orchestration-stack',
    eyebrow: 'ACTO II · ORQUESTACIÓN',
    claim: 'El stack no es una religión. Cada capa cumple un trabajo.',
    narrativeRole: 'Ubicar Codex, Claude Code, Grok, AgentFlow, n8n, MCP y sistemas AEC sin crear un catálogo de logos.',
    evidence: ['S1', 'S13', 'S14', 'S15'],
    speakerIntent: 'Enseñar arquitectura de producto: modelos, orquestación y contexto operativo.',
    transitionIn: 'Team of Experts abre la pregunta por las capas del sistema.',
    transitionOut: 'Las capas se convierten en un loop multiagente con checkpoint y evidencia.',
    durationInFrames: t('orchestration-stack').durationInFrames,
    stableFrame: t('orchestration-stack').stableFrame,
    notes: {
      intent: 'Evitar discusiones de “mejor modelo” y enfocarse en el diseño del flujo.',
      opening: '“Modelos razonan; la orquestación conecta; los sistemas de obra aportan la verdad.”',
      explanation: 'Codex, Claude y Grok pueden colaborar; AgentFlow, n8n y MCP gobiernan conexión; CDE/BIM/ERP aportan contexto.',
      transition: '“Cuando estas capas comparten objetivo y criterio de hecho, aparece un sistema agentic.”',
    },
    render: () => <OrchestrationStack />,
  },
  {
    id: 'multiagent-loop',
    eyebrow: 'ACTO II · SISTEMA AGENTIC',
    claim: 'Muchos agentes solo crean valor cuando comparten un objetivo y un criterio de hecho.',
    narrativeRole: 'Cerrar el acto agentic mostrando especialización, gate humano y evidencia.',
    evidence: ['S1', 'S14'],
    speakerIntent: 'Desinflar el hype de “ejércitos de agentes” y exigir gobernanza observable.',
    transitionIn: 'El stack se observa funcionando como un solo sistema.',
    transitionOut: 'El loop completo abre la definición operativa de AI First.',
    durationInFrames: t('multiagent-loop').durationInFrames,
    stableFrame: t('multiagent-loop').stableFrame,
    notes: {
      intent: 'Mostrar que especialización sin contrato común produce ruido.',
      opening: '“Perceptor, analista, planificador y ejecutor no valen por separado: valen cuando cierran una salida verificable.”',
      explanation: 'El humano aprueba lo irreversible; el sistema registra acción, evidencia y trazabilidad.',
      transition: '“Eso ya no es una herramienta al costado. Es una forma distinta de operar.”',
    },
    render: () => <MultiAgentLoop />,
  },
  {
    id: 'ai-first-operating-model',
    eyebrow: 'ACTO III · AI FIRST',
    claim: 'AI First no es añadir un chatbot. Es rediseñar quién hace qué dentro del flujo.',
    narrativeRole: 'Definir AI First mediante un antes/después operativo.',
    evidence: ['S9', 'S16'],
    speakerIntent: 'Dar una definición clara y no aspiracional de AI First.',
    transitionIn: 'El sistema agentic se convierte en arquitectura de trabajo.',
    transitionOut: 'La definición exige una forma concreta de empezar.',
    durationInFrames: t('ai-first-operating-model').durationInFrames,
    stableFrame: t('ai-first-operating-model').stableFrame,
    notes: {
      intent: 'Distinguir AI First de IA como accesorio.',
      opening: '“AI First significa diseñar el proceso asumiendo inteligencia y humanos en los puntos de juicio.”',
      explanation: 'Antes, la persona coordina herramientas y carga cognitiva. Después, el sistema ejecuta lo repetible y el humano decide lo crítico.',
      transition: '“La pregunta final es cómo comenzar sin transformar toda la empresa de golpe.”',
    },
    render: () => <AiFirstOperatingModel />,
  },
  {
    id: 'first-loop',
    eyebrow: 'ACTO III · PRIMER MOVIMIENTO',
    claim: 'Empieza con un loop interno: un problema, un dueño y una métrica.',
    narrativeRole: 'Convertir la tesis en una unidad mínima implementable y medible.',
    evidence: ['S1', 'S15', 'S16'],
    speakerIntent: 'Dejar una acción concreta para el día siguiente.',
    transitionIn: 'AI First se reduce a un primer flujo controlado.',
    transitionOut: 'La metodología se cierra con evidencia real del portafolio y una invitación comercial.',
    durationInFrames: t('first-loop').durationInFrames,
    stableFrame: t('first-loop').stableFrame,
    notes: {
      intent: 'Evitar pilotos difusos y transformación total prematura.',
      opening: '“Un problema, un dueño, una métrica: ese es el mínimo que permite aprender de verdad.”',
      explanation: 'Definir problema, flujo, agente y evidencia. Medir tiempo de ciclo, error, retrabajo, trazabilidad y adopción.',
      transition: '“GEN+ ya conoce lo que significa convertir trabajo técnico en portafolio. El siguiente paso es convertir procesos en loops.”',
    },
    render: () => <FirstLoop />,
  },
  {
    id: 'proof-closing',
    eyebrow: 'CIERRE · GEN+',
    claim: '¿Quieres ser una más? Empecemos por un problema real.',
    narrativeRole: 'Mover la evidencia de proyectos al final y cerrar con un CTA coherente con la tesis.',
    evidence: ['S15'],
    speakerIntent: 'Demostrar experiencia sin inventar logos y proponer un siguiente paso de bajo riesgo.',
    transitionIn: 'El primer loop conecta con la experiencia acumulada del portafolio GEN+.',
    transitionOut: 'Cierre deliberado: un problema, un dueño, una métrica.',
    durationInFrames: t('proof-closing').durationInFrames,
    stableFrame: t('proof-closing').stableFrame,
    notes: {
      intent: 'Cerrar con prueba operativa y una invitación específica.',
      opening: '“Tenemos 68 proyectos registrados en siete líneas de servicio. La siguiente etapa es convertir experiencia en sistemas repetibles.”',
      explanation: 'Mostrar el corte interno sin atribuir clientes ni resultados no validados. Invitar a diagnosticar un flujo crítico.',
      transition: '“¿Quieres ser una más? Empecemos por un problema real: uno, con dueño y métrica.”',
      warning: 'No mostrar logos de clientes ni atribuir resultados sin autorización y evidencia primaria.',
    },
    render: () => <ProofAndClosing />,
  },
]
