import type { SceneContract } from './types'
import timing from './timing.json'
import {
  AgentAnatomyNine,
  AgentDefinition,
  AiFirstCover,
  AiMomentum,
  AiOpportunity,
  ClosingAiNative,
  GenIntroFilm,
  GenPlusCases,
  HumanCriterion,
  InformationDispersed,
  InnovationAutomationAdapt,
  KeyIdeas,
  MarketGap,
  MaturityLadder,
  MultiAgentTeam,
  OrchestrationStack,
  PromptEngineering,
  TripleImpact,
  VibeCoding,
} from '../scenes/AiFirstKeynote'
import { VisionGrammar } from '../scenes/VisionGrammar'
import { EdgePipeline } from '../scenes/EdgePipeline'

const t = (id: string) => {
  const entry = timing.scenes.find((scene) => scene.id === id)
  if (!entry) throw new Error(`Sin timing para la escena ${id}`)
  return entry
}

export const scenes: SceneContract[] = [
  {
    id: 'cover',
    eyebrow: 'APERTURA',
    claim: 'Implementación AI First, sistemas multiagentes y visión computacional aplicada a la construcción.',
    narrativeRole: 'Título: instala el alcance completo de la ponencia y su promesa.',
    evidence: ['S5'],
    speakerIntent: 'Enmarcar la charla como implementación real, no como panorama de herramientas.',
    transitionIn: 'Desde oscuridad, el título completo con el sello AI FIRST.',
    transitionOut: 'El título cede a la película GEN+ que instala identidad.',
    durationInFrames: t('cover').durationInFrames,
    stableFrame: t('cover').stableFrame,
    notes: {
      intent: 'Prometer un recorrido de implementación: problema → oportunidad → AI First.',
      opening: '“Esta charla no es sobre qué es la IA. Es sobre cómo se implementa en una empresa de construcción.”',
      explanation: 'Presentarse en una frase. Subtítulo: de procesos dispersos a operaciones inteligentes en el sector AEC.',
      transition: '“Antes de empezar, treinta segundos de contexto sobre desde dónde construimos esto.”',
    },
    render: () => <AiFirstCover />,
  },
  {
    id: 'film-gen-intro',
    eyebrow: 'GEN+ · INTRO',
    claim: 'La IA no compite con tu gente. Compite con tu desorden.',
    narrativeRole: 'Única pieza cinematográfica: identidad GEN+ e internal-first sin interrumpir el relato.',
    evidence: ['S5', 'S15'],
    speakerIntent: 'Apertura emocional breve; GEN+ como operación, no como discurso.',
    transitionIn: 'El título se convierte en señales, flujo y acción.',
    transitionOut: 'El logo cede al mapa de tres ideas.',
    durationInFrames: t('film-gen-intro').durationInFrames,
    stableFrame: t('film-gen-intro').stableFrame,
    media: [
      { id: 'clip-opening', kind: 'clip', file: 'media/clips/opening.mp4' },
      { id: 'poster-opening', kind: 'poster', file: 'media/posters/opening.png' },
    ],
    interaction: { kind: 'clip', fallback: 'En movimiento reducido se muestra el poster con la misma tesis.' },
    notes: {
      intent: 'Una sola película para elevar la apertura sin saturar.',
      opening: 'No hablar durante los primeros segundos.',
      explanation: 'El film muestra el paso de información fragmentada a un loop operativo con control humano.',
      transition: '“Ese recorrido tiene tres ideas.”',
      cue: 'Dejar que el film complete un ciclo; avanzar a las tres ideas.',
    },
    render: () => <GenIntroFilm />,
  },
  {
    id: 'key-ideas',
    eyebrow: 'MAPA',
    claim: 'Tres ideas clave: problema, oportunidad y AI First.',
    narrativeRole: 'Explicitar la estructura y la promesa de la ponencia.',
    evidence: ['S8', 'S9'],
    speakerIntent: 'Orientar: cada acto responde una pregunta distinta de la misma tesis.',
    transitionIn: 'La película deja tres conceptos latentes que ahora se nombran.',
    transitionOut: 'La primera idea exige ver dónde vive la información hoy.',
    durationInFrames: t('key-ideas').durationInFrames,
    stableFrame: t('key-ideas').stableFrame,
    notes: {
      intent: 'Estructura simple y acumulativa.',
      opening: '“Tres ideas: la información está dispersa; la IA ya automatiza conocimiento; AI First significa rediseñar procesos.”',
      explanation: 'Problema (dispersión y decisiones tardías) → oportunidad (automatizar conocimiento) → AI First (agentes + visión + procesos rediseñados).',
      transition: '“Empecemos por el problema — y por dónde vive realmente la información de un proyecto.”',
    },
    render: () => <KeyIdeas />,
  },
  {
    id: 'information-dispersed',
    eyebrow: 'ACTO I · EL PROBLEMA CENTRAL',
    claim: 'La información existe, pero no actúa.',
    narrativeRole: 'El corazón del problema: ocho canales que saben algo y ningún sistema que decida.',
    evidence: ['S2', 'S3'],
    speakerIntent: 'Que cada asistente reconozca su proyecto en los ocho canales.',
    transitionIn: 'Las tres ideas aterrizan en la arquitectura real del dato.',
    transitionOut: 'La dispersión se traduce en dolor por nivel: persona, empresa, proyecto.',
    durationInFrames: t('information-dispersed').durationInFrames,
    stableFrame: t('information-dispersed').stableFrame,
    notes: {
      intent: 'Demostrar que el problema no es escasez de datos sino falta de inteligencia operativa.',
      opening: '“¿Dónde vive hoy la verdad de su proyecto? En WhatsApp, Excel, PDFs, planos, modelos, correos, fotos y reuniones.”',
      explanation: 'Cada canal conserva un fragmento. El costo no está en capturar: está en conectar contexto, responsable y cierre.',
      transition: '“Esa fractura no golpea a todos igual. Golpea en tres niveles.”',
    },
    render: () => <InformationDispersed />,
  },
  {
    id: 'triple-impact',
    eyebrow: 'ACTO I · TRES NIVELES',
    claim: 'El mismo problema golpea a la persona, a la empresa y al proyecto.',
    narrativeRole: 'Traducir la fragmentación en consecuencias reconocibles por rol.',
    evidence: ['S3', 'S15'],
    speakerIntent: 'Alinear a toda la sala: cada quien ve una cara del mismo problema.',
    transitionIn: 'La dispersión encuentra sus víctimas.',
    transitionOut: 'El dolor individual se agrega en una paradoja de mercado.',
    durationInFrames: t('triple-impact').durationInFrames,
    stableFrame: t('triple-impact').stableFrame,
    notes: {
      intent: 'Hacer reconocible el dolor sin inventar cifras.',
      opening: '“La persona: tareas repetitivas y reportes manuales. La empresa: procesos desconectados. El proyecto: retrasos y retrabajos.”',
      explanation: 'No son tres problemas: es uno. Información capturada sin sistema que cierre decisiones.',
      transition: '“Y esto ocurre en uno de los mercados más grandes del planeta.”',
    },
    render: () => <TripleImpact />,
  },
  {
    id: 'market-gap',
    eyebrow: 'ACTO I · LA PARADOJA',
    claim: 'Gran mercado, baja productividad.',
    narrativeRole: 'Dimensionar el mercado y la brecha con datos citados.',
    evidence: ['S8'],
    speakerIntent: 'Probar que el problema es económicamente relevante.',
    transitionIn: 'El dolor operativo se agrega en escala macro.',
    transitionOut: 'La brecha abre la pregunta: ¿qué cambió para poder cerrarla?',
    durationInFrames: t('market-gap').durationInFrames,
    stableFrame: t('market-gap').stableFrame,
    notes: {
      intent: 'Instalar la paradoja: escala enorme, mejora lenta, fricción estructural.',
      opening: '“La construcción movió cerca de trece trillones de dólares en 2023 — y su productividad creció 0.4% anual en dos décadas.”',
      explanation: 'Proyección US$22T al 2040. Dolores: baja adopción, planificación débil, control manual, reportes tardíos, decisiones reactivas.',
      transition: '“La frase que resume todo: la obra no falla solo por ejecución; falla por información que llega tarde.”',
      warning: 'Trillón en sentido anglosajón (trillion); al hablar: “13 millones de millones de dólares”.',
    },
    render: () => <MarketGap />,
  },
  {
    id: 'ai-opportunity',
    eyebrow: 'ACTO I · LA OPORTUNIDAD',
    claim: 'La IA convierte datos dispersos en decisiones accionables.',
    narrativeRole: 'El antes/ahora del flujo de decisión: la oportunidad concreta.',
    evidence: ['S9'],
    speakerIntent: 'Mostrar el salto estructural: la interpretación deja de ser el cuello de botella.',
    transitionIn: 'La paradoja encuentra su salida tecnológica.',
    transitionOut: 'Aprovecharla exige distinguir tres verbos que suelen mezclarse.',
    durationInFrames: t('ai-opportunity').durationInFrames,
    stableFrame: t('ai-opportunity').stableFrame,
    notes: {
      intent: 'Contrastar dos cadenas: con y sin IA en el medio.',
      opening: '“Antes: información → interpretación humana → acción tardía. Ahora: información → IA → alerta → decisión → acción.”',
      explanation: 'La IA permite automatizar conocimiento, no solo tareas: interpreta, prioriza y alerta. El criterio sigue siendo humano.',
      transition: '“Para implementarlo bien hay que separar innovar, automatizar y adaptar.”',
    },
    render: () => <AiOpportunity />,
  },
  {
    id: 'innovation-automation-adapt',
    eyebrow: 'ACTO I · MARCO',
    claim: 'Innovar crea valor. Automatizar reduce fricción. Adaptar cambia la curva.',
    narrativeRole: 'Marco de tres verbos que ordena cualquier iniciativa de IA.',
    evidence: ['S9', 'S16'],
    speakerIntent: 'Dar un marco memorable y aplicable el lunes.',
    transitionIn: 'La oportunidad se convierte en tres opciones estratégicas.',
    transitionOut: 'El marco exige mirar el panorama real de la tecnología.',
    durationInFrames: t('innovation-automation-adapt').durationInFrames,
    stableFrame: t('innovation-automation-adapt').stableFrame,
    notes: {
      intent: 'Evitar que toda mejora se llame innovación.',
      opening: '“Innovar: nueva forma de generar valor. Automatizar: menos tareas repetitivas. Adaptar: rediseñar procesos para operar con IA.”',
      explanation: 'El tercer verbo es el decisivo — y el menos practicado.',
      transition: '“La frase incómoda: la IA no mejora procesos rotos; obliga a rediseñarlos.”',
    },
    render: () => <InnovationAutomationAdapt />,
  },
  {
    id: 'ai-momentum',
    eyebrow: 'ACTO I · PANORAMA',
    claim: 'La IA está pasando de herramienta a infraestructura.',
    narrativeRole: 'Panorama actual con cifras citadas y los seis cambios clave.',
    evidence: ['S9', 'S11', 'S12'],
    speakerIntent: 'Crear urgencia con prudencia: dirección validada, implementación abierta.',
    transitionIn: 'El marco necesita el estado real de la tecnología.',
    transitionOut: 'Si la infraestructura cambia, el rol humano también.',
    durationInFrames: t('ai-momentum').durationInFrames,
    stableFrame: t('ai-momentum').stableFrame,
    notes: {
      intent: 'Panorama con fuentes: adopción, capital y seis cambios simultáneos.',
      opening: '“88% de las organizaciones ya usa IA en al menos una función. Y el capital está construyendo infraestructura.”',
      explanation: 'Modelos multimodales, asistentes avanzados, agentes con herramientas, copilotos de código, automatización no-code e IA local.',
      transition: '“¿Y qué le queda al humano en este panorama? Lo más difícil.”',
      warning: 'No presentar inversión como prueba de rentabilidad operativa.',
    },
    render: () => <AiMomentum />,
  },
  {
    id: 'human-criterion',
    eyebrow: 'ACTO I · EL NUEVO ROL',
    claim: 'El humano no compite en velocidad. Compite en criterio.',
    narrativeRole: 'Redefinir el rol profesional: cinco responsabilidades nuevas.',
    evidence: ['S10'],
    speakerIntent: 'Bajar la ansiedad y elevar la vara: el criterio es la nueva ventaja.',
    transitionIn: 'El panorama tecnológico exige reposicionar a la persona.',
    transitionOut: 'Con el rol claro, empieza el recorrido técnico: la escalera de madurez.',
    durationInFrames: t('human-criterion').durationInFrames,
    stableFrame: t('human-criterion').stableFrame,
    notes: {
      intent: 'Complementariedad real, sin triunfalismo ni pánico.',
      opening: '“La IA ya gana pruebas de velocidad. El humano gana donde no hay prueba: en la ambigüedad.”',
      explanation: 'Nuevo rol: entender el problema, definir contexto, validar resultados, diseñar procesos, decidir con responsabilidad.',
      transition: '“Ese criterio se entrena subiendo una escalera. Ocho peldaños.”',
      warning: 'No decir “la IA supera al humano en todo”; el avance es por tarea específica.',
    },
    render: () => <HumanCriterion />,
  },
  {
    id: 'maturity-ladder',
    eyebrow: 'ACTO II · ESCALERA DE MADUREZ',
    claim: 'De usar prompts a rediseñar empresas: ocho peldaños.',
    narrativeRole: 'El mapa del acto II: la progresión completa de madurez IA.',
    evidence: ['S1', 'S13', 'S14'],
    speakerIntent: 'Que cada asistente se ubique en un peldaño y vea el siguiente.',
    transitionIn: 'El nuevo rol necesita una ruta de aprendizaje concreta.',
    transitionOut: 'Los dos primeros peldaños se muestran en detalle.',
    durationInFrames: t('maturity-ladder').durationInFrames,
    stableFrame: t('maturity-ladder').stableFrame,
    notes: {
      intent: 'Dar el mapa completo antes de detallar peldaños.',
      opening: '“¿En qué peldaño está su empresa? Prompt, vibe coding, asistentes, agentes, multiagentes, loops, AI First, AI Native.”',
      explanation: 'Cada peldaño añade autonomía y exige más contexto, permisos y evaluación. Nadie salta peldaños sin pagar el costo después.',
      transition: '“Subamos desde el primero: diseñar instrucciones.”',
    },
    render: () => <MaturityLadder />,
  },
  {
    id: 'prompt-engineering',
    eyebrow: 'ACTO II · NIVEL 01',
    claim: 'Prompt Engineering: no es escribir preguntas, es diseñar instrucciones.',
    narrativeRole: 'El primer peldaño con una especificación de siete campos.',
    evidence: ['S1'],
    speakerIntent: 'Elevar el prompt de truco a especificación profesional.',
    transitionIn: 'La escalera se detiene en su base.',
    transitionOut: 'Si la instrucción crea software, aparece el vibe coding.',
    durationInFrames: t('prompt-engineering').durationInFrames,
    stableFrame: t('prompt-engineering').stableFrame,
    notes: {
      intent: 'Mostrar la anatomía de una instrucción de trabajo real.',
      opening: '“Un buen prompt se parece más a una orden de trabajo que a una pregunta.”',
      explanation: 'Rol, contexto, tarea, datos, formato, restricciones y criterio de validación — con un ejemplo AEC en pantalla.',
      transition: '“Cuando esa instrucción produce software funcional, cambia el juego.”',
    },
    render: () => <PromptEngineering />,
  },
  {
    id: 'vibe-coding',
    eyebrow: 'ACTO II · NIVEL 02',
    claim: 'Vibe Coding: del lenguaje natural al software funcional.',
    narrativeRole: 'El segundo peldaño: dirigir sistemas en lugar de escribir líneas.',
    evidence: ['S13', 'S14'],
    speakerIntent: 'Desmitificar la creación de software: hoy se dirige con lenguaje.',
    transitionIn: 'La instrucción bien diseñada se convierte en producto.',
    transitionOut: 'El siguiente salto: sistemas que no solo se crean, sino que actúan.',
    durationInFrames: t('vibe-coding').durationInFrames,
    stableFrame: t('vibe-coding').stableFrame,
    notes: {
      intent: 'Mostrar el diálogo real humano → herramienta → software.',
      opening: '“Con Codex o Claude Code, un ingeniero describe el dashboard que necesita — y lo obtiene funcionando.”',
      explanation: 'Dashboards, reportes automatizados, APIs conectadas, prototipos y agentes propios: programar se parece a dirigir.',
      transition: '“¿Y si el software además persigue objetivos? Eso es un agente.”',
    },
    render: () => <VibeCoding />,
  },
  {
    id: 'agent-definition',
    eyebrow: 'ACTO II · AGENTES',
    claim: 'Un agente no solo responde: ejecuta.',
    narrativeRole: 'Definir agente con el flujo completo y un encargo AEC real.',
    evidence: ['S1', 'S13'],
    speakerIntent: 'Fijar la diferencia asistente/agente con un ejemplo tangible.',
    transitionIn: 'Del software creado al software que actúa.',
    transitionOut: 'Ejecutar exige piezas: la anatomía completa.',
    durationInFrames: t('agent-definition').durationInFrames,
    stableFrame: t('agent-definition').stableFrame,
    notes: {
      intent: 'Un encargo real recorriendo el flujo de siete pasos.',
      opening: '“Revisa este reporte de obra, detecta riesgos, compáralo con el cronograma y genera alertas. Eso es un encargo, no una pregunta.”',
      explanation: 'Objetivo → contexto → plan → herramientas → acción → verificación → entrega. El agente mantiene estado hasta cerrar.',
      transition: '“¿Qué necesita por dentro para hacerlo de forma confiable? Nueve piezas.”',
    },
    render: () => <AgentDefinition />,
  },
  {
    id: 'agent-anatomy',
    eyebrow: 'ACTO II · ANATOMÍA',
    claim: 'Un agente necesita más que un modelo: nueve piezas.',
    narrativeRole: 'Checklist de compra/diseño: la anatomía completa del agente.',
    evidence: ['S1'],
    speakerIntent: 'Que un directivo sepa qué exigir cuando le vendan “un agente”.',
    transitionIn: 'La definición se abre en componentes.',
    transitionOut: 'Un agente solo no basta: los procesos reales piden equipos.',
    durationInFrames: t('agent-anatomy').durationInFrames,
    stableFrame: t('agent-anatomy').stableFrame,
    notes: {
      intent: 'Checklist mental: si falta una pieza, es una demo.',
      opening: '“Cuando les ofrezcan un agente, pidan ver estas nueve piezas.”',
      explanation: 'Modelo, instrucciones, memoria, contexto, herramientas, permisos, reglas, verificación y salida accionable. Permisos y verificación separan demo de sistema.',
      transition: '“Ahora multipliquen esto por un proceso completo de obra: se necesita un equipo.”',
    },
    render: () => <AgentAnatomyNine />,
  },
  {
    id: 'multiagent-team',
    eyebrow: 'ACTO II · MULTIAGENTES',
    claim: 'Un sistema multiagente es un equipo digital coordinado.',
    narrativeRole: 'El equipo AEC de siete especialistas bajo un orquestador.',
    evidence: ['S1', 'S14'],
    speakerIntent: 'Especialización coordinada, no muchas ventanas de chat.',
    transitionIn: 'La anatomía individual escala a organización.',
    transitionOut: 'El equipo necesita sistema nervioso: orquestación.',
    durationInFrames: t('multiagent-team').durationInFrames,
    stableFrame: t('multiagent-team').stableFrame,
    notes: {
      intent: 'Mostrar el organigrama digital de un proyecto AEC.',
      opening: '“Agente BIM, de costos, de cronograma, normativo, de visión, documental y de reportes — coordinados, no sueltos.”',
      explanation: 'Cada especialista tiene entrada y salida verificable; el orquestador reparte, escala al humano y sintetiza una sola salida.',
      transition: '“¿Y quién conecta todo esto con las apps reales de la empresa?”',
    },
    render: () => <MultiAgentTeam />,
  },
  {
    id: 'orchestration-stack',
    eyebrow: 'ACTO II · ORQUESTACIÓN',
    claim: 'Los agentes necesitan sistema nervioso: n8n y AgentFlow.',
    narrativeRole: 'Las tres capas del stack y las capacidades de orquestación.',
    evidence: ['S1', 'S13', 'S14', 'S15'],
    speakerIntent: 'Arquitectura sin religión de marcas: cada capa cumple un trabajo.',
    transitionIn: 'El equipo digital se conecta al mundo real.',
    transitionOut: 'Con el sistema completo, el acto III baja a la obra: visión y edge.',
    durationInFrames: t('orchestration-stack').durationInFrames,
    stableFrame: t('orchestration-stack').stableFrame,
    notes: {
      intent: 'Enseñar arquitectura: modelos, sistema nervioso, contexto.',
      opening: '“Los modelos razonan. n8n y AgentFlow conectan: apps, flujos, documentos, correos, dashboards y trazabilidad.”',
      explanation: 'Capa 1 modelos/agentes; capa 2 orquestación (n8n · AgentFlow · MCP); capa 3 los sistemas donde vive la verdad operativa.',
      transition: '“Falta el sentido más físico de todos: que la obra pueda verse.”',
    },
    render: () => <OrchestrationStack />,
  },
  {
    id: 'vision-construction',
    eyebrow: 'ACTO III · VISIÓN COMPUTACIONAL',
    claim: 'La obra empieza a verse a sí misma.',
    narrativeRole: 'Visión computacional aplicada: casos de obra sobre un mismo encuadre.',
    evidence: ['S2', 'S3'],
    speakerIntent: 'Aterrizar los casos: EPP, avance, maquinaria, riesgos, inactividad, evidencia.',
    transitionIn: 'Del stack abstracto al sensor más rico: la cámara.',
    transitionOut: '¿Dónde corre esta inteligencia? No siempre en la nube.',
    durationInFrames: t('vision-construction').durationInFrames,
    stableFrame: t('vision-construction').stableFrame,
    interaction: { kind: 'emit-event', fallback: 'El ciclo avanza solo; los chips responden al tacto/click.' },
    notes: {
      intent: 'Vocabulario visual: cuatro operaciones que generan todos los casos.',
      opening: '“Detección de EPP, avance físico, maquinaria, riesgos, inactividad y evidencia automática: todo sale de cuatro operaciones.”',
      explanation: 'Clasificar (qué ocurre), detectar (dónde), segmentar (qué área), seguir (cómo cambia). El caso define la operación.',
      transition: '“Y esta inteligencia puede vivir en la propia obra.”',
      cue: 'Los chips avanzan solos cada ~3 s; tocar uno fija la operación.',
    },
    render: () => <VisionGrammar />,
  },
  {
    id: 'edge-ai',
    eyebrow: 'ACTO III · EDGE AI',
    claim: 'IA local, rápida y privada.',
    narrativeRole: 'Edge AI: el evento nace cerca de la cámara y sobrevive a la mala señal.',
    evidence: ['S2', 'S4'],
    speakerIntent: 'Derribar el mito nube-obligatoria: la IA también vive en obra.',
    transitionIn: 'La visión necesita dónde ejecutarse: cerca de la fuente.',
    transitionOut: 'Con todas las piezas, los casos concretos GEN+/AECODE.',
    durationInFrames: t('edge-ai').durationInFrames,
    stableFrame: t('edge-ai').stableFrame,
    notes: {
      intent: 'Explicar edge en lenguaje operativo, no de hardware.',
      opening: '“En obra la señal se cae. La IA local no: cámara, laptop o Jetson, voz, revisión normativa y alertas sin internet.”',
      explanation: 'El payload viaja: cámara → edge → evento → agente → humano → evidencia. Buffer local y reintentos protegen la evidencia.',
      transition: '“Todo esto ya tiene nombre y apellido en nuestro backlog.”',
    },
    render: () => <EdgePipeline />,
  },
  {
    id: 'genplus-cases',
    eyebrow: 'ACTO III · CASOS GEN+ / AECODE',
    claim: 'Esto no es teoría: es el backlog.',
    narrativeRole: 'Nueve casos aplicables que conectan la charla con la práctica GEN+/AECODE.',
    evidence: ['S15'],
    speakerIntent: 'Credibilidad por especificidad: sistemas con nombre, no promesas.',
    transitionIn: 'La arquitectura completa se vuelve una lista de trabajo real.',
    transitionOut: 'El cierre: hacia dónde va todo esto.',
    durationInFrames: t('genplus-cases').durationInFrames,
    stableFrame: t('genplus-cases').stableFrame,
    notes: {
      intent: 'Recorrer rápido, deteniéndose en dos o tres casos con anécdota propia.',
      opening: '“Estos nueve sistemas están en distintos grados de implementación interna: primero los operamos nosotros.”',
      explanation: 'Siete agentes (reuniones, BIM normativo, metrados, propuestas, reportes, cobranza, académico) + VisionPRO + voz en obra (edge).',
      transition: '“Cierro con la distinción que ordena todo el viaje.”',
      warning: 'No atribuir clientes ni resultados: son sistemas en implementación interna.',
    },
    render: () => <GenPlusCases />,
  },
  {
    id: 'closing',
    eyebrow: 'CIERRE · AI FIRST → AI NATIVE',
    claim: 'La ventaja no será usar IA. Será entender mejor el problema y convertirlo en un sistema inteligente.',
    narrativeRole: 'Cierre: definición AI First vs AI Native, evidencia GEN+ y llamada a la acción.',
    evidence: ['S9', 'S15', 'S16'],
    speakerIntent: 'Dejar la frase final grabada y un siguiente paso de bajo riesgo.',
    transitionIn: 'El backlog abre la pregunta del destino: First o Native.',
    transitionOut: 'Fin. Preguntas.',
    durationInFrames: t('closing').durationInFrames,
    stableFrame: t('closing').stableFrame,
    notes: {
      intent: 'Cerrar con distinción clara, prueba operativa y CTA.',
      opening: '“AI First es usar IA en procesos críticos. AI Native es rediseñar la empresa para operar con datos, agentes y automatización desde el núcleo.”',
      explanation: 'GEN+: 68 proyectos registrados en siete líneas. La invitación: empezar por un problema real — uno, con dueño y métrica.',
      transition: '“La ventaja no será usar IA. Será entender mejor el problema y convertirlo en un sistema inteligente. Gracias.”',
      warning: 'No mostrar logos de clientes ni resultados sin autorización.',
    },
    render: () => <ClosingAiNative />,
  },
]
